# Generated by Neurodocker and Reproenv.

FROM python:3.11-slim-bookworm
ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker
RUN apt-get update -qq \
           && apt-get install -y -q --no-install-recommends \
                  build-essential \
                  curl \
                  g++ \
                  gcc \
                  git \
                  nano \
           && rm -rf /var/lib/apt/lists/*
COPY [".", \
      "/home/repscreen"]
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && /root/.local/bin/uv venv /opt/repscreen
ENV VIRTUAL_ENV="/opt/repscreen"
ENV PATH="/opt/repscreen/bin:/root/.local/bin:$PATH"
ENV SETUPTOOLS_SCM_PRETEND_VERSION_FOR_REPSCREEN="0.1.0+docker"
RUN cd /home/repscreen && uv pip install -e .
ENV IS_DOCKER="1"
RUN test "$(getent passwd repscreen)" \
    || useradd --no-user-group --create-home --shell /bin/bash repscreen
USER repscreen
USER root
RUN chown -R repscreen /home/repscreen
USER repscreen
WORKDIR /home/repscreen
ENTRYPOINT ["/neurodocker/startup.sh"]

# Save specification to JSON.
USER root
RUN printf '{ \
  "pkg_manager": "apt", \
  "existing_users": [ \
    "root" \
  ], \
  "instructions": [ \
    { \
      "name": "from_", \
      "kwds": { \
        "base_image": "python:3.11-slim-bookworm" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "LANG": "en_US.UTF-8", \
        "LC_ALL": "en_US.UTF-8", \
        "ND_ENTRYPOINT": "/neurodocker/startup.sh" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "export ND_ENTRYPOINT=\\"/neurodocker/startup.sh\\"\\napt-get update -qq\\napt-get install -y -q --no-install-recommends \\\\\\n    apt-utils \\\\\\n    bzip2 \\\\\\n    ca-certificates \\\\\\n    curl \\\\\\n    locales \\\\\\n    unzip\\nrm -rf /var/lib/apt/lists/*\\nsed -i -e '"'"'s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/'"'"' /etc/locale.gen\\ndpkg-reconfigure --frontend=noninteractive locales\\nupdate-locale LANG=\\"en_US.UTF-8\\"\\nchmod 777 /opt && chmod a+s /opt\\nmkdir -p /neurodocker\\nif [ ! -f \\"$ND_ENTRYPOINT\\" ]; then\\n  echo '"'"'#!/usr/bin/env bash'"'"' >> \\"$ND_ENTRYPOINT\\"\\n  echo '"'"'set -e'"'"' >> \\"$ND_ENTRYPOINT\\"\\n  echo '"'"'export USER=\\"${USER:=`whoami`}\\"'"'"' >> \\"$ND_ENTRYPOINT\\"\\n  echo '"'"'if [ -n \\"$1\\" ]; then \\"$@\\"; else /usr/bin/env bash; fi'"'"' >> \\"$ND_ENTRYPOINT\\";\\nfi\\nchmod -R 777 /neurodocker && chmod a+s /neurodocker" \
      } \
    }, \
    { \
      "name": "install", \
      "kwds": { \
        "pkgs": [ \
          "git", \
          "gcc", \
          "g++", \
          "curl", \
          "build-essential", \
          "nano" \
        ], \
        "opts": null \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "apt-get update -qq \\\\\\n    && apt-get install -y -q --no-install-recommends \\\\\\n           build-essential \\\\\\n           curl \\\\\\n           g++ \\\\\\n           gcc \\\\\\n           git \\\\\\n           nano \\\\\\n    && rm -rf /var/lib/apt/lists/*" \
      } \
    }, \
    { \
      "name": "copy", \
      "kwds": { \
        "source": [ \
          ".", \
          "/home/repscreen" \
        ], \
        "destination": "/home/repscreen" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "curl -LsSf https://astral.sh/uv/install.sh | sh && /root/.local/bin/uv venv /opt/repscreen" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "VIRTUAL_ENV": "/opt/repscreen" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "PATH": "/opt/repscreen/bin:/root/.local/bin:$PATH" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "SETUPTOOLS_SCM_PRETEND_VERSION_FOR_REPSCREEN": "0.1.0+docker" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "cd /home/repscreen && uv pip install -e ." \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "IS_DOCKER": "1" \
      } \
    }, \
    { \
      "name": "user", \
      "kwds": { \
        "user": "repscreen" \
      } \
    }, \
    { \
      "name": "user", \
      "kwds": { \
        "user": "root" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "chown -R repscreen /home/repscreen" \
      } \
    }, \
    { \
      "name": "user", \
      "kwds": { \
        "user": "repscreen" \
      } \
    }, \
    { \
      "name": "workdir", \
      "kwds": { \
        "path": "/home/repscreen" \
      } \
    }, \
    { \
      "name": "entrypoint", \
      "kwds": { \
        "args": [ \
          "/neurodocker/startup.sh" \
        ] \
      } \
    } \
  ] \
}' > /.reproenv.json
USER repscreen
# End saving to specification to JSON.
