name: tests

# The events/triggers when it should be run
# Here we set that the workflow should run
# whenever there was a push or PR to the
# main branch
on:
  push:
    branches: [main]
  pull_request:

# We define the jobs that should be run
# and the respective runner, ie virtual machine
# Here, the workflow runs on the latest ubuntu
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    # Below we define all steps that should be
    # run within the workflow
    steps:

    # Step 1: Checkout the repository
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    # Step 3: Install dependencies
    - name: Install repscreen package
      run: |
        uv pip install -e ".[dev]" --system

    # Step 4: Run tests with pytest
    - name: Test code
      shell: bash -l {0}
      run: |
        pytest
